# Generated by Django 3.1.3 on 2021-12-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0009_auto_20211213_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='tuition/images/default.jpg', upload_to='tuition/images'),
        ),
    ]
